CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255),
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255),
    role VARCHAR(255),
    status VARCHAR(255),
    CONSTRAINT uk_usuario_email UNIQUE (email)
);

CREATE TABLE acesso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_recurso VARCHAR(255),
    hora_permissao TIMESTAMP(6) WITH TIME ZONE,
    hora_expiracao TIMESTAMP(6) WITH TIME ZONE,
    revogado BOOLEAN NOT NULL,
    usuario_id BIGINT,
    CONSTRAINT fk_acesso_usuario FOREIGN KEY (usuario_id) REFERENCES usuario (id)
);
